### ISSUE TITLE
Install blocked by windows 

### ISSUE THREAD

**Issue by alepmustaqim03** [not-a-human/FinPal#3]
error message : 

This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)

here i provided screenshot from my devices.
I currently run on windows 10 

![Capture12](https://github.com/user-attachments/assets/8e37a0df-2626-40c2-94d9-3a4b1215c237)

**Comment by not-a-human** [comment]
Hi @alepmustaqim03 ,

Thank you for reporting this issue.

It seems that your system does not recognize the program's certificate. I have updated the zip file with a new  `Run.bat `file. . This script will install the necessary certificates required for the application.

Please download the updated zip file and try running the `Run.bat` again. If you encounter any further issues, feel free to reach out.  

Thank you.
Best Regards,
@not-a-human
