### ISSUE TITLE
Bouncing effect when scrolling at the top or bottom in Android.

### ISSUE THREAD

**Issue by SinarUX** [not-a-human/FinPal#9]
https://github.com/user-attachments/assets/89ea5c2a-b475-4f85-bc63-3bedbcbc4538

**Comment by not-a-human** [comment]
Hi @SinarUX ,

Thank you for reporting this issue.

This issue has been fixed and made available in the v1.0.2. Please update it from the Google Play Store with the link below.

https://play.google.com/apps/internaltest/4700306641357890788

Thank you.
Best Regards,
@not-a-human

**Comment by not-a-human** [comment]
Fixed in #11 .
